import type { Metadata } from "next";
import localFont from "next/font/local";
import { Archivo } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import { LanguageProvider } from "@/contexts/LanguageContext";

// Use the Google Font (Archivo)
const archivo = Archivo({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-archivo",
});

const walone_bold = localFont({
  src: "../../public/fonts/Z06-Walone-Bold.ttf",
  display: "swap",
  variable: "--font-z06-walone-bold",
});

const walone_regular = localFont({
  src: "../../public/fonts/Z06-Walone-Regular.ttf",
  display: "swap",
  variable: "--font-z06-walone-regular",
});

const walone_thin = localFont({
  src: "../../public/fonts/Z06-Walone-Thin.ttf",
  display: "swap",
  variable: "--font-z06-walone-thin",
});

export const metadata: Metadata = {
  title: "Japanese Language",
  description: "Generated by Archivo",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html  suppressHydrationWarning>
      <body
        className={`${walone_bold.variable} ${walone_regular.variable} ${walone_thin.variable} ${archivo.variable} antialiased bg-secondary`}
      >
        {" "}
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <LanguageProvider>
          {children}
          </LanguageProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
